FROM python:3.11-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    WORKDIR=/app

WORKDIR ${WORKDIR}

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN useradd -u 8889 workeruser && chown -R workeruser:workeruser ${WORKDIR}
USER workeruser

CMD ["python", "-m", "app.worker.worker"]