services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: docker.io/${DOCKERHUB_USERNAME}/finflow-api:${IMAGE_TAG}

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: docker.io/${DOCKERHUB_USERNAME}/finflow-worker:${IMAGE_TAG}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: docker.io/${DOCKERHUB_USERNAME}/finflow-frontend:${IMAGE_TAG}