[pytest]
testpaths = tests
addopts =
    --cov=app.api.auth
    --cov=app.api.users
    --cov=app.api.jobs
    --cov=app.api.job_events
    --cov=app.api.job_results
    --cov=app.api.financial_data
    --cov=app.core.auth
    --cov=app.core.security
    --cov-branch
    --cov-report=term-missing
    --cov-report=xml
    --cov-report=json
    --cov-fail-under=70
